#using the same file as provided in the server repo
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04   # (recommended) more stable than ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.14"  # pin exact patch if you can
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install gdb
        run: sudo apt-get update && sudo apt-get install -y gdb

      - name: Run pytest under gdb (get backtrace on abort)
        run: |
          gdb -q \
            -ex "run" \
            -ex "bt" \
            -ex "quit" \
            --args python -m pytest -q
